/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package form.author;

import domain.Author;
import communication.Communication;
import componentTable.TableModelAuthor;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import mode.FormMode;

/**
 *
 * @author Jelena
 */
public class frmAuthor extends javax.swing.JDialog {

    /**
     * Creates new form frmNoviAutor
     */
    FormMode formMode;
    Author author;
    TableModelAuthor tma;

    public frmAuthor(java.awt.Frame parent, boolean modal, FormMode formMode, Author author, TableModelAuthor tma) { //, FormMode formMode
        super(parent, modal);
        initComponents();
        this.formMode = formMode;
        this.author = author;
        this.tma = tma;
        setupComponents();
        setTitle("Author");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtFirstname = new javax.swing.JTextField();
        txtLastname = new javax.swing.JTextField();
        btnAdd = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Author", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 18))); // NOI18N

        jLabel1.setText("Firstname:");

        jLabel2.setText("Lastname:");

        btnAdd.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnAdd.setText("Add");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnUpdate.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 100, Short.MAX_VALUE)
                        .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtFirstname, javax.swing.GroupLayout.DEFAULT_SIZE, 248, Short.MAX_VALUE)
                            .addComponent(txtLastname))))
                .addContainerGap(11, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtFirstname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(txtLastname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAdd)
                    .addComponent(btnUpdate))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        try {
            String message = "";
            if (txtFirstname.getText().trim().equals("") || txtFirstname.getText().trim() == null) {
                message += "Enter the author's firstname!\n";
            }
            if (txtLastname.getText().trim().equals("") || txtLastname.getText().trim() == null) {
                message += "Enter the author's lastname!\n";
            }

            if (!message.equals("")) {
                JOptionPane.showMessageDialog(this, message);
            } else {
                author = new Author();
                author.setFirstname(txtFirstname.getText().trim());
                author.setLastname(txtLastname.getText().trim());
                author.setId(Communication.getInstance().addAuthor(author).getId());
                tma.addAuthor(author);
                JOptionPane.showMessageDialog(this, "Author saved successfully!");
                this.dispose();
                txtFirstname.setText("");
                txtLastname.setText("");
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Unable to save author!");
        }
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        try {
            String message = "";
            if (txtFirstname.getText().trim().equals("") || txtFirstname.getText().trim() == null) {
                message += "Enter the author's firstname!\n";
            }
            if (txtLastname.getText().trim().equals("") || txtLastname.getText().trim() == null) {
                message += "Enter the author's lastname!\n";
            }
            if (!message.equals("")) {
                JOptionPane.showMessageDialog(this, message);
            } else {
                Author editedAuthor = new Author();
                editedAuthor.setFirstname(txtFirstname.getText().trim());
                editedAuthor.setLastname(txtLastname.getText().trim());
                editedAuthor.setId(author.getId());
                Communication.getInstance().editAuthor(editedAuthor);
                tma.refreshTable();
                JOptionPane.showMessageDialog(this, "Author saved successfully!");
                this.dispose();

            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Unable to save author!");
        }


    }//GEN-LAST:event_btnUpdateActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtFirstname;
    private javax.swing.JTextField txtLastname;
    // End of variables declaration//GEN-END:variables

    private void setupComponents() {
        switch (formMode) {
            case FORM_ADD:
                btnAdd.setEnabled(true);
                btnUpdate.setEnabled(false);
                txtFirstname.setEnabled(true);
                txtLastname.setEnabled(true);
                break;
            case FORM_EDIT:
                btnAdd.setEnabled(false);
                btnUpdate.setEnabled(true);
                txtFirstname.setEnabled(true);
                txtLastname.setEnabled(true);
                txtFirstname.setText(author.getFirstname());
                txtLastname.setText(author.getLastname());
                break;
            case FORM_VIEW:
                btnAdd.setEnabled(false);
                btnUpdate.setEnabled(false);
                txtFirstname.setEnabled(false);
                txtLastname.setEnabled(false);
                txtFirstname.setText(author.getFirstname());
                txtLastname.setText(author.getLastname());
                break;
        }
    }
}
