/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package form;

import communication.Communication;
import communication.Response;
import componentTable.TableModelAuthor;
import componentTable.TableModelBook;
import componentTable.TableModelMember;
import domain.Administrator;
import form.author.frmAuthor;
import form.author.frmMainAuthors;
import form.book.frmBook;
import form.book.frmMainBook;
import form.member.frmMainMembers;
import form.member.frmMember;
import form.rent.frmMainRental;
import java.net.Socket;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import mode.FormMode;

/**
 *
 * @author Jelena
 */
public class frmMain extends javax.swing.JFrame {

    /**
     * Creates new form frmMain
     */
    Socket socket;
    Administrator administrator;
    TableModelMember tmm;
    TableModelAuthor tma;
    TableModelBook tmb;

    public frmMain(Administrator administrator) {
        try {
            initComponents();
            this.administrator = administrator;
            tmm = new TableModelMember();
            tma = new TableModelAuthor();
            tmb = new TableModelBook();
            prepareView();
            setExtendedState(JFrame.MAXIMIZED_BOTH);
        } catch (Exception ex) {
            Logger.getLogger(frmMain.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblMessage = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtFirstname = new javax.swing.JTextField();
        txtLastname = new javax.swing.JTextField();
        txtUsername = new javax.swing.JTextField();
        btnLogOut = new javax.swing.JButton();
        menuBarMain = new javax.swing.JMenuBar();
        menuAuthor = new javax.swing.JMenu();
        menuItemNewAuthor = new javax.swing.JMenuItem();
        menuItemAuthors = new javax.swing.JMenuItem();
        menuBook = new javax.swing.JMenu();
        menuItemNewBook = new javax.swing.JMenuItem();
        menuItemBooks = new javax.swing.JMenuItem();
        menuMembers = new javax.swing.JMenu();
        menuItemNewMember = new javax.swing.JMenuItem();
        menuItemMembers = new javax.swing.JMenuItem();
        menuRental = new javax.swing.JMenu();
        menuItemRentals = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Administrator", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 20))); // NOI18N

        lblMessage.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblMessage.setText("Welcome, this is your information:");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Firstname:");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("Lastname:");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setText("Username:");

        btnLogOut.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnLogOut.setText("Log out");
        btnLogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogOutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 110, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(111, 111, 111)
                                .addComponent(txtUsername))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(27, 27, 27)
                                .addComponent(txtFirstname))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(29, 29, 29)
                                .addComponent(txtLastname))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(btnLogOut))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(lblMessage)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtFirstname, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtLastname, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(btnLogOut)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        menuAuthor.setText("Author");

        menuItemNewAuthor.setText("New author");
        menuItemNewAuthor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemNewAuthorActionPerformed(evt);
            }
        });
        menuAuthor.add(menuItemNewAuthor);

        menuItemAuthors.setText("Authors");
        menuItemAuthors.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemAuthorsActionPerformed(evt);
            }
        });
        menuAuthor.add(menuItemAuthors);

        menuBarMain.add(menuAuthor);

        menuBook.setText("Book");

        menuItemNewBook.setText("New book");
        menuItemNewBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemNewBookActionPerformed(evt);
            }
        });
        menuBook.add(menuItemNewBook);

        menuItemBooks.setText("Books");
        menuItemBooks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemBooksActionPerformed(evt);
            }
        });
        menuBook.add(menuItemBooks);

        menuBarMain.add(menuBook);

        menuMembers.setText("Member");

        menuItemNewMember.setText("New member");
        menuItemNewMember.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemNewMemberActionPerformed(evt);
            }
        });
        menuMembers.add(menuItemNewMember);

        menuItemMembers.setText("Members");
        menuItemMembers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemMembersActionPerformed(evt);
            }
        });
        menuMembers.add(menuItemMembers);

        menuBarMain.add(menuMembers);

        menuRental.setText("Rental");

        menuItemRentals.setText("Rentals");
        menuItemRentals.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemRentalsActionPerformed(evt);
            }
        });
        menuRental.add(menuItemRentals);

        menuBarMain.add(menuRental);

        setJMenuBar(menuBarMain);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(50, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuItemMembersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemMembersActionPerformed
        (new frmMainMembers(this, true, administrator)).setVisible(true);
    }//GEN-LAST:event_menuItemMembersActionPerformed

    private void menuItemAuthorsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemAuthorsActionPerformed
        (new frmMainAuthors(this, true)).setVisible(true);
    }//GEN-LAST:event_menuItemAuthorsActionPerformed

    private void menuItemNewAuthorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemNewAuthorActionPerformed
        (new frmAuthor(this, true, FormMode.FORM_ADD, null, tma)).setVisible(true);
    }//GEN-LAST:event_menuItemNewAuthorActionPerformed

    private void menuItemNewBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemNewBookActionPerformed
        (new frmBook(this, true, FormMode.FORM_ADD, null, tmb)).setVisible(true);
    }//GEN-LAST:event_menuItemNewBookActionPerformed

    private void menuItemBooksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemBooksActionPerformed
        (new frmMainBook(this, true)).setVisible(true);
    }//GEN-LAST:event_menuItemBooksActionPerformed

    private void menuItemNewMemberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemNewMemberActionPerformed
        (new frmMember(this, true, FormMode.FORM_ADD, null, tmm)).setVisible(true);
    }//GEN-LAST:event_menuItemNewMemberActionPerformed

    private void btnLogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogOutActionPerformed
        int result = JOptionPane.showConfirmDialog(this, "Are you sure you want to log out of the system?", "Confirmation", JOptionPane.YES_NO_OPTION);

        if (result == JOptionPane.NO_OPTION) {
            return;
        }

        if (result == JOptionPane.YES_OPTION) {
            try {
                Response response = Communication.getInstance().logoff(administrator);
                JOptionPane.showMessageDialog(this, response.getException());
                new frmLogin().setVisible(true);
                this.dispose();
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, "It's not possible to log out!");
            }
        }
    }//GEN-LAST:event_btnLogOutActionPerformed

    private void menuItemRentalsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemRentalsActionPerformed
        (new frmMainRental(this, true)).setVisible(true);
    }//GEN-LAST:event_menuItemRentalsActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed

    }//GEN-LAST:event_formWindowClosed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogOut;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblMessage;
    private javax.swing.JMenu menuAuthor;
    private javax.swing.JMenuBar menuBarMain;
    private javax.swing.JMenu menuBook;
    private javax.swing.JMenuItem menuItemAuthors;
    private javax.swing.JMenuItem menuItemBooks;
    private javax.swing.JMenuItem menuItemMembers;
    private javax.swing.JMenuItem menuItemNewAuthor;
    private javax.swing.JMenuItem menuItemNewBook;
    private javax.swing.JMenuItem menuItemNewMember;
    private javax.swing.JMenuItem menuItemRentals;
    private javax.swing.JMenu menuMembers;
    private javax.swing.JMenu menuRental;
    private javax.swing.JTextField txtFirstname;
    private javax.swing.JTextField txtLastname;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables

    private void prepareView() {
        txtFirstname.setText(administrator.getFirstname());
        txtLastname.setText(administrator.getLastname());
        txtUsername.setText(administrator.getUsername());

        txtFirstname.setEditable(false);
        txtLastname.setEditable(false);
        txtUsername.setEditable(false);

    }
}
